baseURL = "https://blog.vorona.me/"
languageCode = "en-us"
title = "No.Try not. Do… or do not. There is no try."
theme = "archie"
author = "Anatolii Vorona"
copyright = "Copyright © 2020–2022, Anatolii Vorona; all rights reserved."
canonifyurls = true
pagination.pagerSize = 4
enableRobotsTXT = true
googleAnalytics = "G-4NT8K1F5CV"
googleAnalyticsAsync = true
    
[params]

    description = "Hugo is a general-purpose website framework. Technically speaking, Hugo is a static site generator. Unlike systems that dynamically build a page with each visitor request, Hugo builds pages when you create or update your content. Since websites are viewed far more often than they are edited, Hugo is designed to provide an optimal viewing experience for your website’s end users and an ideal writing experience for website authors."
    mainSection = "posts"
    postsOnHomePage = 8
    rss = true

    [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

    [[menu.main]]
    name = "All posts"
    url = "/posts/"
    weight = 2

    [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

#     [[menu.main]]
#     name = "About"
#     url = "/about/"
#     weight = 4

    [[params.social]]
      name = "github"
      link = "https://github.com/BOPOHA/"

    [[params.social]]
      name = "email"
      link = "blog@vorona.me"

#     [[params.social]]
#       name = "linkedin"
#       link = "https://www.linkedin.com/in/.../"
